# Generated by Django 4.2.30 on 2026-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email_confirmation_token",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Токен подтверждения email",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="email_confirmation_token_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время создания токена"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_email_confirmed",
            field=models.BooleanField(default=False, verbose_name="Email подтвержден"),
        ),
    ]
